[Variables]
Bands=81
BarGap=8
BarWidth=16
BarHeight=500
MinBarHeight=1
PaletteColor1=255,255,255
FFTSize=2048
FFTBufferSize=8192
AverageSize=0
Colors=Single
PaletteColor2=96,160,224
PaletteColor3=255,160,160
PaletteColor4=240,240,240
TransitionTime=12
hBlendingMultiplier=0
vBlendingMultiplier=0
OpacityLower=255
OpacityUpper=255
OpacityMultiplier=1
DecayEffect=0
DecayThreshold=55
DecaySustain=365
DecayDuration=635
DecayOpacityMin=0
DecayOpacityMax=255
bFXGhost=1
nFXGhostAttack=2375
nFXGhostDecay=950
ColorsExclude=
ModeKeyboard=0
FirstBandIndex=1

; to find device ID, see device manager -> device want to use -> Details -> Children -> 
; SWD\MMDEVAPI\{0.0.0.00000000}.{c8daff22-9442-4afd-a15e-5ba3ab6c888b} -> take the final ID 
; so in this case {0.0.0.00000000}.{c8daff22-9442-4afd-a15e-5ba3ab6c888b} 

; !!! DO NOT CHANGE BELOW
SkinGroup=FountainOfColors
Config=Fountain of Colors
SetCloneColorState=
Angle=0
Invert=0
Channel=
Port=
ID={0.0.0.00000000}.{c8daff22-9442-4afd-a15e-5ba3ab6c888b}
